### PR TITLE
Default external-authentication-uid to null on update

### PR DESCRIPTION
**Pull request by marcparadise**
Looks like the last trailing edge - when a user was updaetd via PUT, the value "undefined" was getting captured for `external_authentication_uid`.  This fixes that.   This also provides consistent behavior with new_record re: recovery-auth-enabled, by forcing the value to true/false.

ping @opscode/server-team

### CODE REVIEW

**Comment by seth** [comment]
LGTM

**Comment by oferrigni** [comment]
Why not a test for this?

**Comment by marcparadise** [comment]
@oferrigni agreed and done! 
@jmink the opposite - a non-null (<<"undefined">>) is causing us to go down the external authentication path when we don't want to.

**Comment by jmink** [comment]
Understood.  Just wanted to make sure it wasn't making a new problem.  LGTM.

**Comment by oferrigni** [comment]
Thx!!

**Pull request merged**
