### PR TITLE
in chef_user, make email validation case insensitive. test for the same

### PR DESCRIPTION
**Pull request by marcparadise**
Production issue found where a user previously saved with mixed-case email (which is valid) could not perform password recovery because automatic validation of that same email was failing. 

This change makes email validation properly case-insensitive, and adds a test to verify the same.

### CODE REVIEW

**Comment by jmink** [comment]
:+1:

**Comment by sdelano** [comment]
:thumbsup: after updated comments

**Comment by sdelano** [comment]
:shipit:

**Comment by marcparadise** [comment]
Comments updated, will pull into a release pending travis

**Pull request merged**
