### PR TITLE
allow 'test' and 'spec' segments for upload

### PR DESCRIPTION
**Pull request by lamont-granquist**
:warning: :construction: WIP

### CODE REVIEW

**Comment by lamont-granquist** [comment]
This is a PR for one way of addressing CHEF-4044 and addressing efforts to integrate testing in Chef runs better.

There's also thoughts about adding an "all_files" field which would deprecate the entire concept of segments and allow knife cookbook upload to upload arbitrary files to a cookbook.  There's also thoughts about adding an "other_files" field which would be similar but would be subtractive of the the files that are already classified in segments.  And on the gripping hand, there could be an "all_files" field added which was composed of "other_files" when uploading from Chef 12 clients and in Chef 13 becomes "all_files" for real.

cc @opscode/client-engineers @opscode/server-team

**Comment by lamont-granquist** [comment]
There's one last idea which is fairly easy to reject which is to remove any key filtering and allow the client to upload whatever it likes at the top level keys of the json post and then synchronize those down, but that road winds up with sort of method_missing kind of smell on it, and issues with someone uploading "json_class/foo.erb" or "cookbook_name/thingy.rb" where the segments collide with reserved keys.

**Comment by marcparadise** [comment]
@lamont-granquist I'm closing this as this code now all lives in oc_erchef.  However, this is relatively recent, is this we decided we need? If so, it's worth making the oc_erchef changes and going through review/merging.

**Comment by lamont-granquist** [comment]
Yeah, since we're all not in silos any more I'm going to push this through as an RFC and then make the patches to the server.  It'll probably be the "all_files" alternative with backcompat where the server will accept either segments or "all_files" and then will serve both back, and the client/knife will preferentially use "all_files" when the server supports it.

**Pull request closed without merging**
